name: Python CI with uv

on:
  workflow_dispatch:
    branches: [ "github-action" ]

jobs:
  run-bin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Create venv and install dependencies
        run: uv sync --frozen

      - name: Run bin.py
        run: |
          uv run github_pr_reviewer/main.py 'Can you please review this PR: https://github.com/neha-duggirala/Github-issue-resolver/pull/4 and add a review comment?' --verbose
        env:
          MODEL: ${{ secrets.MODEL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.pr-review-pat }}
